### ISSUE TITLE
PUT requests should contain person uuid

### ISSUE THREAD

**Issue by mfalthaw** [agriculture-capstone/agriboard#100]
The url in the `update` method of CoreAPI doesn't include the Person's uuid when fetching an update request. Please refer to API docs for reference: https://boresha.live:18888/#api-People-UpdatePerson.

Assigning this to @Right2Drive assuming he built this portion?

**Comment by Right2Drive** [comment]
Again if this is something you need to use feel free to edit the module yourself

**Comment by mfalthaw** [comment]
I think this is a missing from the `CoreAPI` module, and given that you built the `CoreAPI` module I assume that you'd know your way around it better.

I actually tried playing with it a little bit but couldn't get it to work.

**Comment by Right2Drive** [comment]
I have enough on my plate as far as the web project right now, if this is blocking you the code in the CoreAPI is not that complicated, I'm sure you can figure it out if you set your mind to it.

**Comment by mfalthaw** [comment]
Sounds good, I’ll ask you questions when I get stuck.
